// src/components/more.vue
<template>
  <div class="container">
    <div class="row py-3">
      <h1 class="ME">Some More?</h1>
      <p class="ME_sub">좀 더 저에 대해서 알고 싶나요? 밑에 사이트를 방문해주세요!</p>
    </div>
    <div class="container">
      <div class="row">
        <div
          class="col-md-11 col-lg-12 col-xl-11"
          style="margin-left: auto; margin-left: auto"
        >
          <div class="row">
            <div class="col-md-4 col-lg-5">
              <div class="card more_card">
                <div class="card-body card_center" >
                  <p class="card-title" style="font-size: 50px ; font-weight: Bold;"><i class="bi bi-github"></i> Github</p>
                  <h6 class="text-muted card-subtitle mb-2">
                    <a href="https://github.com/INMD1"
                      >https://github.com/INMD1</a
                    >
                  </h6>
                  <p class="card-text">이때 까지 만든 코드를 올리는 사이트</p>
                  <ul>
                    <li>CLI 프로그램 소스코드</li>
                    <li>학교 실습 소스코드</li>
                    <li>웹앱 프로그램 소스코드</li>
                    <li>SNS 봇 프로그램 소스코드</li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-1"></div>
            <div class="col-md-4 col-lg-5">
              <div class="card more_card">
                <div class="card-body card_center">
                  <p class="card-title" style="font-size: 50px ; font-weight: Bold;"><i class="bi bi-archive"></i> Amview</p>
                  <h6 class="text-muted card-subtitle mb-2">
                    <a href="https://amview.powerinmd.com"
                      >https://amview.powerinmd.com</a
                    >
                  </h6>
                  <p class="card-text">
                    코딩 문제를 풀고 소스코드를 공개하는 사이트
                  </p>
                  <ul>
                    <li>백준 문제 소스코드</li>
                    <li>라비다 문제 소스코드</li>
                    <li>Ascode 문제 소스코드</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {};
</script>

// src/componets/more.tsx
import React from "react";
import {
  HStack,
  Card,
  VStack,
  List,
  Text,
  Heading,
  Center,
  Link,
} from "@chakra-ui/react";
import { FaBoxArchive } from "react-icons/fa6";
import { FaGithubSquare } from "react-icons/fa";

const More = () => {
  return (
    <div className="p-10 sm:p-48" style={{ backgroundColor: "#749BC2" }}>
      <div className="pb-10">
        <center>
          <p className="text-4xl md:text-6xl font-bold">Some More?</p>
          <br/>
          <Text as="b" fontSize="xl">
            좀 더 저에 대해서 알고 싶나요? 밑에 사이트를 방문해주세요!
          </Text>
        </center>
      </div>
      <div className="flex grid gap-10 sm:grid-cols-2">
        <div className="grid-cols-1">
          <Card.Root>
            <Card.Body>
              <Center>
                <VStack>
                  <HStack>
                    <FaGithubSquare style={{ height: "6vh", width: "auto" }} />
                    <Heading size="xl">Github</Heading>
                  </HStack>
                  <Link href="https://github.com/INMD1">
                    <Text>https://github.com/INMD1</Text>
                  </Link>
                  <Text>코딩 문제를 풀고 소스코드를 공개하는 사이트</Text>
                  <List.Root>
                    <List.Item>백준 문제 소스코드</List.Item>
                    <List.Item>라비다 문제 소스코드</List.Item>
                    <List.Item>Ascode 문제 소스코드</List.Item>
                  </List.Root>
                </VStack>
              </Center>
            </Card.Body>
          </Card.Root>
        </div>
        <div className="grid-cols-1">
          <Card.Root>
            <Card.Body>
              <Center>
                <VStack>
                  <HStack>
                    <FaBoxArchive style={{ height: "6vh", width: "auto" }} />
                    <Heading size="xl">Amview</Heading>
                  </HStack>
                  <Link href="https://amview.powerinmd.com">
                    <Text>https://amview.powerinmd.com</Text>
                  </Link>
                  <Text>코딩 문제를 풀고 소스코드를 공개하는 사이트</Text>

                  <List.Root>
                    <List.Item>백준 문제 소스코드</List.Item>
                    <List.Item>라비다 문제 소스코드</List.Item>
                    <List.Item>Ascode 문제 소스코드</List.Item>
                  </List.Root>
                </VStack>
              </Center>
            </Card.Body>
          </Card.Root>
        </div>
      </div>
    </div>
  );
};

export default More;
