// src/componets/skill.tsx
import React from "react";
import { FaVuejs, FaReact, FaUbuntu } from "react-icons/fa";
import {
  SiRockylinux,
  SiJavascript,
  SiAndroidstudio,
  SiIntellijidea,
  SiProxmox,
} from "react-icons/si";
import { DiVisualstudio } from "react-icons/di";
import { VscVscode } from "react-icons/vsc";
import { BsBootstrapFill } from "react-icons/bs";
import { TbBrandKotlin } from "react-icons/tb";
import { FaNode } from "react-icons/fa6";

const Skill = () => {
  return (
    <div
      id="skill"
      className="h-full"
      style={{ padding: "10%", backgroundColor: "#DCE2F0" }}
    >
      <p className="text-6xl font-bold">DEVELOPMENT SKILLS</p>
      <br />
      <p>아래에 있는 것들은 제가 프로젝트를 할때 써본 기술들입니다.</p>
      <p>다른 업무나 협업 할때 쉽게 프로젝트를 이해할수 있습니다.</p>
      <div className="jb-division-line" />
      <p className="font-bold text-3xl">lang / FrameWork</p>
      <br />
      <div className="grid md:grid-flow-col md:grid-rows-2 gap-7">
        <div className="grid justify-center justify-items-center">
          <FaVuejs style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Vue</p>
          <p>웹개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <FaReact style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">React</p>
          <p>웹개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <SiJavascript style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Javascript</p>
          <p>프론트및 백엔드 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <BsBootstrapFill style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Bootstrap</p>
          <p>프론트 디자인활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <TbBrandKotlin style={{ height: "2.5=rem", width: "auto" }} />
          <p className="font-bold">Kotlin</p>
          <p>안드로이드 개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <FaNode style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Node.js</p>
          <p>CLI/Express Api/사이트 개발</p>
        </div>
      </div>
      <br />
      <div className="jb-division-line" />
      <p className="font-bold text-3xl">IDE</p>
      <br />
      <div className="grid md:grid-flow-col gap-7">
        <div className="grid justify-center justify-items-center">
          <DiVisualstudio style={{ height: "2rem", width: "auto" }} />
          <p className="font-bold">Visual studio</p>

          <p>C/C++ 개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <VscVscode style={{ height: "2rem", width: "auto" }} />
          <p className="font-bold">Visual studio Code</p>

          <p>웹 개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <SiIntellijidea style={{ height: "2rem", width: "auto" }} />
          <p className="font-bold">intellij</p>

          <p>코틀린/자바 단일 개발 활용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <SiAndroidstudio style={{ height: "2rem", width: "auto" }} />
          <p className="font-bold">Android studio</p>

          <p>안드로이드 앱 개발 활용</p>
        </div>
      </div>
      <div className="jb-division-line" />
      <p className="font-bold text-3xl">Other</p>
      <br />
      <div className=" grid md:grid-flow-col gap-7">
        <div className="grid justify-center justify-items-center">
          <FaUbuntu style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Ubuntu</p>
          <p>서버 운용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <SiRockylinux style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Rocky Linux</p>
          <p>서버 운용</p>
        </div>
        <div className="grid justify-center justify-items-center">
          <SiProxmox style={{ height: "2.5rem", width: "auto" }} />
          <p className="font-bold">Proxmox</p>
          <p>서버 운용</p>
        </div>
      </div>
    </div>
  );
};

export default Skill;

// src/components/skill.vue
<template>
  <div class="h-100 align-items-center d-flex">
    <div class="container">
      <div class="row">
        <div class="py-5">
          <h1 class="skill_top">DEVELOPMENT SKILLS</h1>
          <p class="skill_low">
            아래에 있는 것들은 제가 프로젝트를 할때 써본 기술들입니다.<br />
            그래서 다른 프로젝트에 가도 코드를 이해할수 있습니다.
          </p>
          <h3 style="font-weight: bold">lang / FrameWork / CMS</h3>
          <hr />
          <div class="row">
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/Vue.png" /> Vue
              </h5>
              <h6 class="text-muted card-subtitle mb-2">Router 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/javascript.png" class="icon" />
                javascript
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                자바스크립트 문법 활용
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/nodejs.png" />
                Node.js
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                CLI, Express Api/사이트 개발
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/bootstrap.png" />
                Bootstrap
              </h5>
              <h6 class="text-muted card-subtitle mb-2">웹 디자인 활용</h6>
            </div>
          </div>
          <div class="row py-3">
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/kotlin.png" />Kotlin
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                안드로이드 개발 활용
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/html.png" class="icon" />
                HTML
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                태그를 활용한 마크업
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/vuetify.png" />
                vuetify
              </h5>
              <h6 class="text-muted card-subtitle mb-2">웹 디자인 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/java.png" />
                Java
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                안드로이드/기타 프로그램 활용
              </h6>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/css.png" class="icon" /> CSS
              </h5>
              <h6 class="text-muted card-subtitle mb-2">웹 디자인 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/ionic.png" class="icon" /> Ionic
              </h5>
              <h6 class="text-muted card-subtitle mb-2">하이브리앱 개발 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/lang/strapi.png" class="icon" /> Strapi
              </h5>
              <h6 class="text-muted card-subtitle mb-2">백엔드 API서버 활용</h6>
            </div>
          </div>
          <h3 style="padding-top: 3rem; font-weight: bold">IDE</h3>
          <hr />
          <div class="row">
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/program/vs.png" class="icon" /> Visual
                Studio
              </h5>
              <h6 class="text-muted card-subtitle mb-2">C언어 개발 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/program/vs.png" class="icon" /> Visual
                Studio code
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                Js/html/등 개발 활용
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/program/android.png" class="icon" />
                android studio
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                안드로이드앱 개발 활용
              </h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/program/intellij.png" class="icon" />
                intellij
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                코틀린/자바 개발 활용
              </h6>
            </div>
          </div>

          <h3 style="padding-top: 3rem; font-weight: bold">Other</h3>
          <hr />
          <div class="row">
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/OS/Ubuntu.png" class="icon" />Ubuntu
              </h5>
              <h6 class="text-muted card-subtitle mb-2">서버운용 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/OS/linux.png" class="icon" />Rocky Linux
              </h5>
              <h6 class="text-muted card-subtitle mb-2">서버운용 활용</h6>
            </div>
            <div class="col-md-3">
              <h5 class="card-title" style="font-weight: bold">
                <img src="../assets/img/program/git.png" class="icon" />Git
              </h5>
              <h6 class="text-muted card-subtitle mb-2">
                기본내용 숙지/깃허브 활용
              </h6>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script></script>
